title: Andiamo Live
email: contacto@trazos.club
description: > # this means to ignore newlines until "baseurl:"
  Página Madre de Trazos Club y Andiamo.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  andiamo

sass: 
  style: compressed

### exclude the instructions / write-up in the README.md
exclude:
- README.md
- Gemfile
- Gemfile.lock

highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md


# Tracker
#analytics: UA-83979019-1

# Comments
#disqus-shortname: webjeda-demo

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []